substitutions:
  _MONGODB_CONNECTION: ""
  _GCS_BUCKET_NAME: ""
  _GCS_FOLDER: ""

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west9-docker.pkg.dev/translation-471323/etl-docker-repo/etl-gcs-uploader:latest',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west9-docker.pkg.dev/translation-471323/etl-docker-repo/etl-gcs-uploader:latest'
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      [
        '-c',
        "gcloud run jobs deploy etl-gcs-uploader-job --image europe-west9-docker.pkg.dev/translation-471323/etl-docker-repo/etl-gcs-uploader:latest --region europe-west1 --project translation-471323 --service-account etl-gcs-uploader@translation-471323.iam.gserviceaccount.com --set-env-vars MONGODB_CONNECTION=\"${_MONGODB_CONNECTION}\",GCS_BUCKET_NAME=\"${_GCS_BUCKET_NAME}\",GCS_FOLDER=\"${_GCS_FOLDER}\""
      ]

images:
  - 'europe-west9-docker.pkg.dev/translation-471323/etl-docker-repo/etl-gcs-uploader:latest'
