dbt_translations_marts:
  outputs:
    dev:
      dataset: dbt_translations_marts
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\hp\OneDrive\Bureau\projects\end-to-end-ELT-pipline\dbt-bigquery\credentials.json
      location: EU
      method: service-account
      priority: interactive
      project: wissem-school
      threads: 1
      type: bigquery
  target: dev